-- CertTrack - Database Schema and Sample Data
-- Training Compliance Management System for Construction Sites
-- Student: Vinicius Monteiro de Brito, 25124021, HDSDEV_SEP25

-- Creating the database
CREATE DATABASE IF NOT EXISTS certtrack;
USE certtrack;

-- Employee table to stores all construction workers and subcontractors
-- Worker ID (employee_ref) is auto-generated by the system

CREATE TABLE employees (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  name          VARCHAR(150) NOT NULL,
  employee_ref  VARCHAR(50)  NOT NULL UNIQUE,
  email         VARCHAR(150),
  company       VARCHAR(150),
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Projects table to store all construction sites/projects
CREATE TABLE projects (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  name        VARCHAR(150) NOT NULL,
  location    VARCHAR(150),
  status      ENUM('active', 'closed') DEFAULT 'active',
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Training_types table to store all types of training certificates used on Irish construction sites
-- validity_months defines how long each certificate is valid
-- mandatory_default = true means required on all sites by law

CREATE TABLE training_types (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  name             VARCHAR(150) NOT NULL UNIQUE,
  validity_months  INT NOT NULL,
  mandatory_default BOOLEAN DEFAULT FALSE
);


-- Users table: 
-- Stores login credentials for admins and employees
-- Admins have full access, employees can only view their own certificates
-- employee_id links to the employees table for worker accounts
CREATE TABLE users (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  name          VARCHAR(150) NOT NULL,
  email         VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role          ENUM('admin', 'employee') DEFAULT 'employee',
  employee_id   INT DEFAULT NULL,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE SET NULL
);


-- project_employees table:
-- Links workers to construction projects
-- A worker can be assigned to multiple projects
CREATE TABLE project_employees (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  project_id  INT NOT NULL,
  employee_id INT NOT NULL,
  assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (project_id)  REFERENCES projects(id)  ON DELETE CASCADE,
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);


-- project_training_requirements Table:
-- Defines which training types are mandatory for each project

CREATE TABLE project_training_requirements (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  project_id       INT NOT NULL,
  training_type_id INT NOT NULL,
  FOREIGN KEY (project_id)       REFERENCES projects(id)       ON DELETE CASCADE,
  FOREIGN KEY (training_type_id) REFERENCES training_types(id) ON DELETE CASCADE
);

-- certificates Table:
-- Stores all training certificates uploaded by admins
-- OCR raw text is stored for reference
-- Status is calculated automatically based on expiry date

CREATE TABLE certificates (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  employee_id      INT NOT NULL,
  training_type_id INT NOT NULL,
  issue_date       DATE NOT NULL,
  expiry_date      DATE NOT NULL,
  file_path        VARCHAR(255),
  ocr_raw_text     TEXT,
  status           ENUM('valid', 'expiring_soon', 'expired') DEFAULT 'valid',
  uploaded_by      INT NOT NULL,
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (employee_id)      REFERENCES employees(id)      ON DELETE CASCADE,
  FOREIGN KEY (training_type_id) REFERENCES training_types(id) ON DELETE CASCADE,
  FOREIGN KEY (uploaded_by)      REFERENCES users(id)          ON DELETE RESTRICT
);

-- alert_logs Table:
-- Tracks which expiry alerts have already been sent
-- Prevents duplicate email alerts being sent every day

CREATE TABLE alert_logs (
  id             INT AUTO_INCREMENT PRIMARY KEY,
  certificate_id INT NOT NULL,
  type           ENUM('expiring_soon', 'expired') NOT NULL,
  sent_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (certificate_id) REFERENCES certificates(id) ON DELETE CASCADE
);

-- Sample Data

-- Training types used on Irish construction sites
INSERT INTO training_types (name, validity_months, mandatory_default) VALUES
('Safe Pass', 48, true),
('Manual Handling', 36, true),
('Working at Heights', 36, false),
('Abrasive Wheels', 60, false),
('First Aid', 24, false),
('Slinger Signaller', 60, false),
('Confined Spaces', 36, false),
('Fire Safety', 12, false);

-- Sample employees (Worker IDs auto-generated by system)
INSERT INTO employees (name, employee_ref, email, company) VALUES
('Josh Connolly', 'CT001', 'josh.josh1213@gmail.com', 'Company1'),
('Alisson John', 'CT002', 'aliali@test.com', 'Company2'),
('John Killen', 'CT003', 'johnxxhshs67@hotmail.com', 'Company1'),
('Patrick Patricio', 'CT004', 'pat_pattest565@gmail.com', 'Company2'),
('Anne Marie', 'CT005', 'anne_testtest3@gmail.com', 'Company3');

-- Sample projects
INSERT INTO projects (name, location, status) VALUES
('CSE_Connolly Station Extension', 'Dublin 1', 'active'),
('MHP4_Mater Hospital Phase 4', 'Dublin 7', 'active'),
('UGM_University of Galway Modernisation', 'Galway', 'active'),
('CXCX Building', 'Cork', 'active');

-- Admin user (password: admin123)
INSERT INTO users (name, email, password_hash, role, employee_id) VALUES
('Admin User', 'admin@certtrack.com', '$2b$10$/MURQFOslS0bVyUZoKNq0OQtAG5EPmnmq2.MIFJJiCPa.t1oXxnPe', 'admin', NULL);

-- Employee user for Josh Connolly (password: worker123)
INSERT INTO users (name, email, password_hash, role, employee_id) VALUES
('Josh Connolly', 'josh@certtrack.com', '$2b$10$WuWRaDTXT2urlM8QDE7EP.cbpoW462OoTWqa44TXR2Ri8rIf.g2I.', 'employee', 1);